---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero
  require_chef_omnibus: '13.12.3'

platforms:
  - name: centos-7.5
    driver:
      box: bento/centos-7.5

suites:
  - name: default
    run_list:
      - recipe[packer]
