---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 15.6.10
  chef_license: 'accept-no-persist'

platforms:
  - name: centos-7.7
    driver:
      box: bento/centos-7.7

suites:
  - name: default
    run_list:
      - recipe[packer]
