---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  require_chef_omnibus: '13.12.3'

platforms:
  - name: centos-7.7
    driver:
      box: bento/centos-7.7

suites:
  - name: default
    run_list:
      - recipe[packer]
